/* globals before, describe, it */

var assert = require('assert')
var marky = require('..')
var fixtures = require('./fixtures')

describe('sanitize', function () {
  var $

  before(function () {
    $ = marky(fixtures.dirty)
  })

  it('removes script tags', function () {
    assert(~fixtures.dirty.indexOf('<script'))
    assert(!$('script').length)
  })

  it('can be disabled to allow input from trusted sources', function () {
    assert(~fixtures.dirty.indexOf('<script'))
    var $ = marky(fixtures.dirty, {sanitize: false})
    assert.equal($('script').length, 1)
    assert.equal($("script[src='http://malware.com']").length, 1)
    assert.equal($("script[type='text/javascript']").length, 1)
    assert.equal($("script[charset='utf-8']").length, 1)
  })

  it('allows img tags', function () {
    assert($('img').length)
    assert.equal($('img').attr('width'), '600')
    assert.equal($('img').attr('height'), '400')
    assert.equal($('img').attr('valign'), 'middle')
    assert.equal($('img').attr('onclick'), undefined)
  })

  it('allows h1/h2/h3/h4/h5/h6 tags to preserve their dom id', function () {
    assert($('h1[id]').length)
    assert($('h2[id]').length)
    assert($('h3[id]').length)
    assert($('h4[id]').length)
    assert($('h5[id]').length)
    assert($('h6[id]').length)
  })

  it('removes classnames from elements', function () {
    assert(~fixtures.dirty.indexOf('class="xxx"'))
    assert(!$('.xxx').length)
  })

  it('allows classnames on div tags used for syntax highlighting', function () {
    assert($('div.highlight').length)
  })

  it('allows the <s> strikethrough element', function () {
    assert(~fixtures.dirty.indexOf('~~orange~~'))
    assert.equal($('s').text(), 'orange')
  })

  it('disallows iframes from sources other than youtube', function () {
    var $ = marky(fixtures.basic)
    assert(~fixtures.basic.indexOf('<iframe src="//www.youtube.com/embed/3I78ELjTzlQ'))
    assert(~fixtures.basic.indexOf('<iframe src="//malware.com'))
    assert.equal($('iframe').length, 2)
    assert.equal($('iframe').eq(0).attr('src'), '//www.youtube.com/embed/3I78ELjTzlQ')
    assert.equal($('iframe').eq(1).attr('src'), 'https://www.youtube.com/embed/DN4yLZB1vUQ')
  })

  it('allows the <ins> element', function () {
    assert(~fixtures.dirty.indexOf('<ins>'))
    assert.equal($('ins').text(), 'inserted')
  })

  it('allows the <del> element', function () {
    assert(~fixtures.dirty.indexOf('<del>'))
    assert.equal($('del').text(), 'deleted')
  })

  it('allows the <sub> element', function () {
    assert(~fixtures.dirty.indexOf('<sub>'))
    assert.equal($('sub').text(), 'subscript')
  })

  it('allows the <sup> element', function () {
    assert(~fixtures.dirty.indexOf('<sup>'))
    assert.equal($('sup').text(), 'superscript')
  })

  it('allows the <dl> element', function () {
    assert(~fixtures.dirty.indexOf('<dl>'))
  })

  it('allows the <dt> element', function () {
    assert(~fixtures.dirty.indexOf('<dt>'))
    assert.equal($('dt').eq(0).text(), 'Term 1')
  })

  it('allows the <dd> element', function () {
    assert(~fixtures.dirty.indexOf('<dd>'))
    assert.equal($('dd').eq(0).text(), 'Definition 1')
  })

  it('allows table cell left alignment', function () {
    var html = marky(fixtures.dirty).html()
    assert(html.indexOf('<th style="text-align:left">') > -1)
    assert(html.indexOf('<td style="text-align:left">') > -1)
  })

  it('allows table cell right alignment', function () {
    var html = marky(fixtures.dirty).html()
    assert(html.indexOf('<th style="text-align:right">') > -1)
    assert(html.indexOf('<td style="text-align:right">') > -1)
  })

  it('allows table cell center alignment', function () {
    var html = marky(fixtures.dirty).html()
    assert(html.indexOf('<th style="text-align:center">') > -1)
    assert(html.indexOf('<td style="text-align:center">') > -1)
  })

  it('strips non-alignment table cell style', function () {
    var html = marky(fixtures.dirty).html()
    assert(!~html.indexOf('color:red;'))
    assert(!~html.indexOf('width: 100%;'))

    // alignment directives generated by something other than markdown-it's
    // parser might contain internal whitespace; we normalize it such that our
    // sanitized output contains none
    assert(!~html.indexOf('text-align: right'))
  })

  it('allows title attributes on images', function () {
    var title = 'Image title'
    var $ = marky("![alt text](#url '" + title + "')")
    assert.equal($('img').attr('title'), title)
  })

  it('allows title attributes on links', function () {
    var title = "You don't know npm"
    var $ = marky('[link text](https://www.youtube.com/watch?v=Zqm78_27lWA "' + title + '")')
    assert.equal($('a').attr('title'), title)
  })
})
