var sanitizeHtml = require("sanitize-html")

module.exports = function(html) {
  return sanitizeHtml(html, {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat([
      "h1",
      "h2",
      "img",
      "meta",
      "span"
    ]),
    allowedClasses: {
      code: [
        "hljs",
        "bash",
        "css",
        "coffeescript",
        "glsl",
        "http",
        "js",
        "javascript",
        "json",
        "lang-html",
        "sh",
        "shell",
        "typescript",
        "xml",
      ],
      span: [
        'hljs-addition',
        'hljs-annotaion',
        'hljs-annotation',
        'hljs-argument',
        'hljs-array',
        'hljs-at_rule',
        'hljs-attr_selector',
        'hljs-attribute',
        'hljs-begin-block',
        'hljs-blockquote',
        'hljs-body',
        'hljs-built_in',
        'hljs-bullet',
        'hljs-cbracket',
        'hljs-cdata',
        'hljs-cell',
        'hljs-change',
        'hljs-char',
        'hljs-chunk',
        'hljs-class',
        'hljs-code',
        'hljs-collection',
        'hljs-command',
        'hljs-commands',
        'hljs-commen',
        'hljs-comment',
        'hljs-constant',
        'hljs-container',
        'hljs-dartdoc',
        'hljs-date',
        'hljs-decorator',
        'hljs-default',
        'hljs-deletion',
        'hljs-doctype',
        'hljs-emphasis',
        'hljs-end-block',
        'hljs-envvar',
        'hljs-expression',
        'hljs-filename',
        'hljs-filter',
        'hljs-flow',
        'hljs-foreign',
        'hljs-formula',
        'hljs-func',
        'hljs-function',
        'hljs-function_name',
        'hljs-generics',
        'hljs-header',
        'hljs-hexcolor',
        'hljs-horizontal_rule',
        'hljs-id',
        'hljs-import',
        'hljs-important',
        'hljs-infix',
        'hljs-inheritance',
        'hljs-input',
        'hljs-javadoc',
        'hljs-javadoctag',
        'hljs-keyword',
        'hljs-keywords',
        'hljs-label',
        'hljs-link_label',
        'hljs-link_reference',
        'hljs-link_url',
        'hljs-list',
        'hljs-literal',
        'hljs-localvars',
        'hljs-long_brackets',
        'hljs-matrix',
        'hljs-module',
        'hljs-number',
        'hljs-operator',
        'hljs-output',
        'hljs-package',
        'hljs-param',
        'hljs-parameter',
        'hljs-params',
        'hljs-parent',
        'hljs-phpdoc',
        'hljs-pi',
        'hljs-pod',
        'hljs-pp',
        'hljs-pragma',
        'hljs-preprocessor',
        'hljs-prompt',
        'hljs-property',
        'hljs-pseudo',
        'hljs-quoted',
        'hljs-record_name',
        'hljs-regex',
        'hljs-regexp',
        'hljs-request',
        'hljs-reserved',
        'hljs-rest_arg',
        'hljs-rules',
        'hljs-shader',
        'hljs-shading',
        'hljs-shebang',
        'hljs-special',
        'hljs-sqbracket',
        'hljs-status',
        'hljs-stl_container',
        'hljs-stream',
        'hljs-string',
        'hljs-strong',
        'hljs-sub',
        'hljs-subst',
        'hljs-summary',
        'hljs-symbol',
        'hljs-tag',
        'hljs-template_comment',
        'hljs-template_tag',
        'hljs-title',
        'hljs-type',
        'hljs-typedef',
        'hljs-typename',
        'hljs-value',
        'hljs-var_expand',
        'hljs-variable',
        'hljs-winutils',
        'hljs-xmlDocTag',
        'hljs-yardoctag'
      ],
      h1: ['deep-link'],
      h2: ['deep-link'],
      h3: ['deep-link'],
      h4: ['deep-link'],
      h5: ['deep-link'],
      h6: ['deep-link'],
    },
    allowedAttributes: {
      h1: ["id"],
      h2: ["id"],
      h3: ["id"],
      h4: ["id"],
      h5: ["id"],
      h6: ["id"],
      a: ["href", "id", "name", "target"],
      img: ["id", "src"],
      meta: ["name", "content"]
    }
  })
}
